/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export interface AddressRequest {
  label: string;
  recipientName: string;
  phone: string;
  formattedAddress: string;
  /** @nullable */
  commune: string | null;
  /** @nullable */
  province: string | null;
  /** @nullable */
  placeId: string | null;
  isDefault: boolean;
}
