/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export interface BannerPayloadDto {
  title: string;
  /** @nullable */
  subtitle: string | null;
  imageUrl: string;
  /** @nullable */
  linkUrl: string | null;
  sortOrder: number;
  isActive: boolean;
}
