/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export interface CartItemDto {
  productId?: string;
  productName?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  productPrice?: number | string;
  productImageUrl?: string[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  quantity?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  currentStockQuantity?: number | string;
}
