/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */
import type { CartItemDto } from './cartItemDto';

export interface CartDto {
  id?: string;
  userId?: string;
  items?: CartItemDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  totalPrice?: number | string;
}
