/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export interface CartItemDto {
  productId: string;
  productName: string;
  productPrice: number;
  productImageUrl: string;
  unitCo2Saved: number;
  quantity: number;
  currentStockQuantity: number;
}
