/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */
import type { CouponDiscountTypeEnum } from './couponDiscountTypeEnum';

export interface CouponDto {
  id: string;
  code: string;
  discountType: CouponDiscountTypeEnum;
  discountValue: number;
  minOrderAmount: number;
  maxUses: number;
  usedCount: number;
  expiresAt: Date;
  isActive: boolean;
  createdAt: Date;
}
