/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export interface CreateGreenWalletCommandResponse {
  id: string;
  userId: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  balance: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  earnedTotal: number | string;
  /** @nullable */
  updatedAt: string | null;
}
