/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */
import type { OrderStatusEnum } from './orderStatusEnum';

export interface CreateOrderCommandResponse {
  id: string;
  userId: string;
  status: OrderStatusEnum;
  deliveryAddress: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  discountAmount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  earnedPoints: number | string;
  createdAt: string;
}
