/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export interface CreateGreenWalletCommandResponse {
  id: string;
  userId: string;
  balance: number;
  earnedTotal: number;
  /** @nullable */
  updatedAt: string | null;
}
