/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */
import type { PaymentMethodEnum } from './paymentMethodEnum';
import type { PaymentStatusEnum } from './paymentStatusEnum';

export interface CreatePaymentCommandResponse {
  id: string;
  orderId: string;
  method: PaymentMethodEnum;
  status: PaymentStatusEnum;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  amount: number | string;
  createdAt: string;
}
