/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export type DocumentFileTypeEnum = typeof DocumentFileTypeEnum[keyof typeof DocumentFileTypeEnum];


export const DocumentFileTypeEnum = {
  Pdf: 'Pdf',
  Docx: 'Docx',
  Txt: 'Txt',
} as const;
