/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */
import type { CouponDiscountTypeEnum } from './couponDiscountTypeEnum';

export type GetAllCouponsParams = {
search?: string;
isActive?: boolean;
discountType?: CouponDiscountTypeEnum;
};
