/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export type GetApiAdminAnalystParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
Month: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
Year: number | string;
};
