/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export type GetApiProductsSomeParams = {
PageSize?: number;
PageNumber?: number;
SearchTerm?: string;
CategoryId?: string;
MinPrice?: number;
MaxPrice?: number;
SortBy?: string;
IsDescending?: boolean;
IsOrganic?: boolean;
IsBiodegradable?: boolean;
IsRecycled?: boolean;
};
