/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */
import type { MaterialTypeEnum } from './materialTypeEnum';
import type { ProductSortBy } from './productSortBy';

export type GetAllProductsParams = {
sortBy?: ProductSortBy;
sortDescending?: boolean;
search?: string;
categoryIds?: string[];
materialIds?: string[];
isOrganic?: boolean;
isBiodegradable?: boolean;
isRecycled?: boolean;
materialTypes?: MaterialTypeEnum[];
minPrice?: number;
maxPrice?: number;
pageNumber?: number;
pageSize?: number;
};
