/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */
import type { OrderSortBy } from './orderSortBy';

export type GetAllOrdersParams = {
SortBy?: OrderSortBy;
SortDescending?: boolean;
UserId?: string;
PageNumber?: number;
PageSize?: number;
};
