/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */
import type { ProductSortBy } from './productSortBy';

export type GetApiProductsParams = {
SortBy?: ProductSortBy;
SortDescending?: boolean;
Search?: string;
CategoryIds?: string[];
IsOrganic?: boolean;
IsBiodegradable?: boolean;
IsRecycled?: boolean;
MinPrice?: number;
MaxPrice?: number;
PageNumber?: number;
PageSize?: number;
};
