/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */
import type { GetInfoAnalystQueryCo2Saved } from './getInfoAnalystQueryCo2Saved';
import type { GetInfoAnalystQueryOrders } from './getInfoAnalystQueryOrders';
import type { GetInfoAnalystQueryRevenue } from './getInfoAnalystQueryRevenue';
import type { GetInfoAnalystQueryUsers } from './getInfoAnalystQueryUsers';

export interface GetInfoAnalystQueryResponse {
  totalRevenue: GetInfoAnalystQueryRevenue;
  amountOrders: GetInfoAnalystQueryOrders;
  amountUsers: GetInfoAnalystQueryUsers;
  totalCo2Saved: GetInfoAnalystQueryCo2Saved;
}
