/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export interface GetInfoAnalystQueryResponse {
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  totalRevenue: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  amountOrders: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  amountUsers: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  totalCo2Saved: number | string;
}
