/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */
import type { Co2Saved } from './co2Saved';
import type { Orders } from './orders';
import type { Revenue } from './revenue';
import type { Users } from './users';

export interface GetInfoAnalystQueryResponse {
  totalRevenue: Revenue;
  amountOrders: Orders;
  amountUsers: Users;
  totalCo2Saved: Co2Saved;
}
