/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export interface GetMyStatisticsQuerySummary {
  totalOrders: number;
  totalSpending: number;
  paidSpending: number;
  pendingSpending: number;
  refundPendingSpending: number;
  totalCo2Saved: number;
  currentPoints: number;
  lifetimePoints: number;
}
