/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */
import type { GetMyStatisticsQueryCategorySlice } from './getMyStatisticsQueryCategorySlice';
import type { GetMyStatisticsQueryMonthlyPoint } from './getMyStatisticsQueryMonthlyPoint';
import type { GetMyStatisticsQueryStatusSlice } from './getMyStatisticsQueryStatusSlice';
import type { GetMyStatisticsQuerySummary } from './getMyStatisticsQuerySummary';

export interface GetMyStatisticsQueryResponse {
  summary: GetMyStatisticsQuerySummary;
  monthlySpending: GetMyStatisticsQueryMonthlyPoint[];
  categoryBreakdown: GetMyStatisticsQueryCategorySlice[];
  statusBreakdown: GetMyStatisticsQueryStatusSlice[];
}
