/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * GreenEcoCommerce.WebAPI | v1
 * OpenAPI spec version: 1.0.0
 */

export interface LoginCommand {
  email: string;
  password: string;
}
