/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */
import type { MaterialTypeEnum } from './materialTypeEnum';

export interface MaterialItem {
  id: string;
  name: string;
  type: MaterialTypeEnum;
  ecoRating: number;
  /** @nullable */
  origin: string | null;
  /** @nullable */
  sku: string | null;
  stockQty: number;
  /** @nullable */
  unit: string | null;
  unitPrice: number;
  /** @nullable */
  imageUrl: string | null;
}
