/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export interface MaterialUpdateDto {
  name: string;
  type: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  ecoRating: number | string;
  /** @nullable */
  origin: string | null;
  /** @nullable */
  sku: string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  stockQty: number | string;
  /** @nullable */
  unit: string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  unitPrice: number | string;
  /** @nullable */
  imageUrl: string | null;
}
