/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export type MaterialTypeEnum = typeof MaterialTypeEnum[keyof typeof MaterialTypeEnum];


export const MaterialTypeEnum = {
  Natural: 'Natural',
  Synthetic: 'Synthetic',
  Recycled: 'Recycled',
} as const;
