/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */
import type { NotificationTypeEnum } from './notificationTypeEnum';

export interface NotificationDto {
  id: string;
  title: string;
  message: string;
  type: NotificationTypeEnum;
  /** @nullable */
  link: string | null;
  isRead: boolean;
  createdAt: Date;
}
