/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export type OrderSortBy = typeof OrderSortBy[keyof typeof OrderSortBy];


export const OrderSortBy = {
  CreatedAt: 'CreatedAt',
  TotalAmount: 'TotalAmount',
} as const;
