/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export interface OrderItemDto {
  productId: string;
  productName: string;
  /** @nullable */
  productImage: string | null;
  quantity: number;
  unitPrice: number;
  unitCo2Saved: number;
}
