/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export type OrderStatusEnum = typeof OrderStatusEnum[keyof typeof OrderStatusEnum];


export const OrderStatusEnum = {
  Pending: 'Pending',
  Packing: 'Packing',
  Delivering: 'Delivering',
  Delivered: 'Delivered',
  Cancelled: 'Cancelled',
} as const;
