/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */
import type { OrderItemDto } from './orderItemDto';
import type { OrderStatusEnum } from './orderStatusEnum';
import type { PaymentMethodEnum } from './paymentMethodEnum';
import type { PaymentStatusEnum } from './paymentStatusEnum';

export interface OrderDto {
  id: string;
  userId: string;
  status: OrderStatusEnum;
  deliveryAddress: string;
  totalAmount: number;
  finalAmount: number;
  discountAmount: number;
  totalCo2Saved: number;
  earnedPoints: number;
  items: OrderItemDto[];
  createdAt: Date;
  paymentStatus: PaymentStatusEnum;
  paymentMethod: PaymentMethodEnum;
}
