/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */
import type { NotificationDto } from './notificationDto';

export interface PagedResultOfNotificationDto {
  items: NotificationDto[];
  totalCount: number;
  pageNumber: number;
  pageSize: number;
  readonly totalPages: number;
}
