/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */
import type { OrderDto } from './orderDto';

export interface PagedResultOfOrderDto {
  items: OrderDto[];
  totalCount: number;
  pageNumber: number;
  pageSize: number;
  readonly totalPages: number;
}
