/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export type PaymentStatusEnum = typeof PaymentStatusEnum[keyof typeof PaymentStatusEnum];


export const PaymentStatusEnum = {
  Pending: 'Pending',
  Paid: 'Paid',
  Refunded: 'Refunded',
  Failed: 'Failed',
} as const;
