/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export interface ProductPayloadDto {
  name: string;
  /** @nullable */
  description: string | null;
  price: number;
  stockQty: number;
  categoryId: string;
  carbonIndex: number;
  baselineCarbonIndex: number;
  decomposePercent: number;
  recyclePercent: number;
  imageUrl: string[];
  materialIds: string[];
}
