/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */
import type { MaterialItem } from './materialItem';

export interface ProductDto {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  price: number;
  stockQty: number;
  categoryId: string;
  carbonIndex: number;
  baselineCarbonIndex: number;
  decomposePercent: number;
  recyclePercent: number;
  imageUrl: string[];
  materials: MaterialItem[];
  isActive: boolean;
}
