/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export interface ProductDto {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  price: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  stockQty: number | string;
  categoryId: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  carbonIndex: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  baselineCarbonIndex: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  decomposePercent: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  recyclePercent: number | string;
  imageUrl: string[];
  isActive: boolean;
}
