/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * GreenEcoCommerce.WebAPI | v1
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterCommand {
  firstName: string;
  lastName: string;
  phone: string;
  address: string;
  /** @nullable */
  role: string | null;
  email: string;
  password: string;
}
