/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export interface Revenue {
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  currentValue: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  previousValue: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  growthPercentage: number | string;
  isGrowth: boolean;
}
