/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export interface ReviewDto {
  id: string;
  userId: string;
  userName: string;
  productId: string;
  rating: number;
  comment: string;
  isApproved: boolean;
  isHidden: boolean;
  createdAt: Date;
}
