/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export interface UpdateUserProfileCommand {
  id: string;
  avatar: string;
  firstName: string;
  lastName: string;
  password: string;
  phone: string;
  address: string;
}
