/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

export type UserSortBy = typeof UserSortBy[keyof typeof UserSortBy];


export const UserSortBy = {
  FirstName: 'FirstName',
  LastName: 'LastName',
  Points: 'Points',
} as const;
