/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * GreenEcoCommerce API
 * API GreenEcoCommerce app - app for buying and selling green products
 * OpenAPI spec version: v1
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { useMutation, useQuery } from '@tanstack/react-query'
import { customInstance } from '../lib/axios'
import type {
  CategoryDto,
  CategoryPayloadDto,
  CreateMaterialCommand,
  CreateMaterialResponse,
  GetApiProductsParams,
  GetApiProductsSomeParams,
  LoginCommand,
  MaterialItem,
  MaterialUpdateDto,
  ProblemDetails,
  ProductDto,
  ProductPayloadDto,
  RegisterCommand,
  RegisterResponse,
  UpdateInfoUserDto,
  UpdateInfoUserResponse,
  UserInfoResponse,
  UserProfileResponse,
} from './schemas'
export const getApiCategories = (signal?: AbortSignal) => {
  return customInstance<CategoryDto[]>({ url: `/api/categories`, method: 'GET', signal })
}

export const getGetApiCategoriesQueryKey = () => {
  return [`/api/categories`] as const
}

export const getGetApiCategoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiCategories>>,
  TError = ProblemDetails,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategories>>, TError, TData>>
}) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetApiCategoriesQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCategories>>> = ({ signal }) => getApiCategories(signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiCategories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCategories>>>
export type GetApiCategoriesQueryError = ProblemDetails

export function useGetApiCategories<TData = Awaited<ReturnType<typeof getApiCategories>>, TError = ProblemDetails>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategories>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategories>>,
          TError,
          Awaited<ReturnType<typeof getApiCategories>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategories<TData = Awaited<ReturnType<typeof getApiCategories>>, TError = ProblemDetails>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategories>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategories>>,
          TError,
          Awaited<ReturnType<typeof getApiCategories>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategories<TData = Awaited<ReturnType<typeof getApiCategories>>, TError = ProblemDetails>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategories>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCategories<TData = Awaited<ReturnType<typeof getApiCategories>>, TError = ProblemDetails>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategories>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiCategoriesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const postApiCategories = (categoryPayloadDto: CategoryPayloadDto, signal?: AbortSignal) => {
  return customInstance<CategoryDto>({
    url: `/api/categories`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: categoryPayloadDto,
    signal,
  })
}

export const getPostApiCategoriesMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiCategories>>,
    TError,
    { data: CategoryPayloadDto },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiCategories>>,
  TError,
  { data: CategoryPayloadDto },
  TContext
> => {
  const mutationKey = ['postApiCategories']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCategories>>, { data: CategoryPayloadDto }> = (
    props,
  ) => {
    const { data } = props ?? {}

    return postApiCategories(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostApiCategoriesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCategories>>>
export type PostApiCategoriesMutationBody = CategoryPayloadDto
export type PostApiCategoriesMutationError = ProblemDetails

export const usePostApiCategories = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiCategories>>,
      TError,
      { data: CategoryPayloadDto },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postApiCategories>>, TError, { data: CategoryPayloadDto }, TContext> => {
  return useMutation(getPostApiCategoriesMutationOptions(options), queryClient)
}

export const getApiCategoriesId = (id: string, signal?: AbortSignal) => {
  return customInstance<CategoryDto>({ url: `/api/categories/${id}`, method: 'GET', signal })
}

export const getGetApiCategoriesIdQueryKey = (id: string) => {
  return [`/api/categories/${id}`] as const
}

export const getGetApiCategoriesIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiCategoriesId>>,
  TError = void | ProblemDetails,
>(
  id: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoriesId>>, TError, TData>> },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetApiCategoriesIdQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCategoriesId>>> = ({ signal }) =>
    getApiCategoriesId(id, signal)

  return { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiCategoriesId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCategoriesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCategoriesId>>>
export type GetApiCategoriesIdQueryError = void | ProblemDetails

export function useGetApiCategoriesId<
  TData = Awaited<ReturnType<typeof getApiCategoriesId>>,
  TError = void | ProblemDetails,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoriesId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoriesId>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoriesId>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoriesId<
  TData = Awaited<ReturnType<typeof getApiCategoriesId>>,
  TError = void | ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoriesId>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoriesId>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoriesId>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoriesId<
  TData = Awaited<ReturnType<typeof getApiCategoriesId>>,
  TError = void | ProblemDetails,
>(
  id: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoriesId>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCategoriesId<
  TData = Awaited<ReturnType<typeof getApiCategoriesId>>,
  TError = void | ProblemDetails,
>(
  id: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoriesId>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiCategoriesIdQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const putApiCategoriesId = (id: string, categoryPayloadDto: CategoryPayloadDto, signal?: AbortSignal) => {
  return customInstance<CategoryDto>({
    url: `/api/categories/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: categoryPayloadDto,
    signal,
  })
}

export const getPutApiCategoriesIdMutationOptions = <TError = void | ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiCategoriesId>>,
    TError,
    { id: string; data: CategoryPayloadDto },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiCategoriesId>>,
  TError,
  { id: string; data: CategoryPayloadDto },
  TContext
> => {
  const mutationKey = ['putApiCategoriesId']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiCategoriesId>>,
    { id: string; data: CategoryPayloadDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return putApiCategoriesId(id, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutApiCategoriesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiCategoriesId>>>
export type PutApiCategoriesIdMutationBody = CategoryPayloadDto
export type PutApiCategoriesIdMutationError = void | ProblemDetails

export const usePutApiCategoriesId = <TError = void | ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiCategoriesId>>,
      TError,
      { id: string; data: CategoryPayloadDto },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiCategoriesId>>,
  TError,
  { id: string; data: CategoryPayloadDto },
  TContext
> => {
  return useMutation(getPutApiCategoriesIdMutationOptions(options), queryClient)
}

export const deleteApiCategoriesId = (id: string, signal?: AbortSignal) => {
  return customInstance<void>({ url: `/api/categories/${id}`, method: 'DELETE', signal })
}

export const getDeleteApiCategoriesIdMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiCategoriesId>>, TError, { id: string }, TContext>
}): UseMutationOptions<Awaited<ReturnType<typeof deleteApiCategoriesId>>, TError, { id: string }, TContext> => {
  const mutationKey = ['deleteApiCategoriesId']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiCategoriesId>>, { id: string }> = (props) => {
    const { id } = props ?? {}

    return deleteApiCategoriesId(id)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteApiCategoriesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiCategoriesId>>>

export type DeleteApiCategoriesIdMutationError = ProblemDetails

export const useDeleteApiCategoriesId = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiCategoriesId>>, TError, { id: string }, TContext>
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteApiCategoriesId>>, TError, { id: string }, TContext> => {
  return useMutation(getDeleteApiCategoriesIdMutationOptions(options), queryClient)
}

export const getApiMaterials = (signal?: AbortSignal) => {
  return customInstance<MaterialItem[]>({ url: `/api/materials`, method: 'GET', signal })
}

export const getGetApiMaterialsQueryKey = () => {
  return [`/api/materials`] as const
}

export const getGetApiMaterialsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiMaterials>>,
  TError = ProblemDetails,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaterials>>, TError, TData>>
}) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetApiMaterialsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMaterials>>> = ({ signal }) => getApiMaterials(signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiMaterials>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiMaterialsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMaterials>>>
export type GetApiMaterialsQueryError = ProblemDetails

export function useGetApiMaterials<TData = Awaited<ReturnType<typeof getApiMaterials>>, TError = ProblemDetails>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaterials>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMaterials>>,
          TError,
          Awaited<ReturnType<typeof getApiMaterials>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMaterials<TData = Awaited<ReturnType<typeof getApiMaterials>>, TError = ProblemDetails>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaterials>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMaterials>>,
          TError,
          Awaited<ReturnType<typeof getApiMaterials>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMaterials<TData = Awaited<ReturnType<typeof getApiMaterials>>, TError = ProblemDetails>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaterials>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiMaterials<TData = Awaited<ReturnType<typeof getApiMaterials>>, TError = ProblemDetails>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaterials>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiMaterialsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const postApiMaterials = (createMaterialCommand: CreateMaterialCommand, signal?: AbortSignal) => {
  return customInstance<CreateMaterialResponse>({
    url: `/api/materials`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createMaterialCommand,
    signal,
  })
}

export const getPostApiMaterialsMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiMaterials>>,
    TError,
    { data: CreateMaterialCommand },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiMaterials>>,
  TError,
  { data: CreateMaterialCommand },
  TContext
> => {
  const mutationKey = ['postApiMaterials']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiMaterials>>, { data: CreateMaterialCommand }> = (
    props,
  ) => {
    const { data } = props ?? {}

    return postApiMaterials(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostApiMaterialsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiMaterials>>>
export type PostApiMaterialsMutationBody = CreateMaterialCommand
export type PostApiMaterialsMutationError = ProblemDetails

export const usePostApiMaterials = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiMaterials>>,
      TError,
      { data: CreateMaterialCommand },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiMaterials>>,
  TError,
  { data: CreateMaterialCommand },
  TContext
> => {
  return useMutation(getPostApiMaterialsMutationOptions(options), queryClient)
}

export const getApiMaterialsId = (id: string, signal?: AbortSignal) => {
  return customInstance<MaterialItem>({ url: `/api/materials/${id}`, method: 'GET', signal })
}

export const getGetApiMaterialsIdQueryKey = (id: string) => {
  return [`/api/materials/${id}`] as const
}

export const getGetApiMaterialsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiMaterialsId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaterialsId>>, TError, TData>> },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetApiMaterialsIdQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMaterialsId>>> = ({ signal }) =>
    getApiMaterialsId(id, signal)

  return { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiMaterialsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiMaterialsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMaterialsId>>>
export type GetApiMaterialsIdQueryError = ProblemDetails

export function useGetApiMaterialsId<TData = Awaited<ReturnType<typeof getApiMaterialsId>>, TError = ProblemDetails>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaterialsId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMaterialsId>>,
          TError,
          Awaited<ReturnType<typeof getApiMaterialsId>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMaterialsId<TData = Awaited<ReturnType<typeof getApiMaterialsId>>, TError = ProblemDetails>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaterialsId>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMaterialsId>>,
          TError,
          Awaited<ReturnType<typeof getApiMaterialsId>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMaterialsId<TData = Awaited<ReturnType<typeof getApiMaterialsId>>, TError = ProblemDetails>(
  id: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaterialsId>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiMaterialsId<TData = Awaited<ReturnType<typeof getApiMaterialsId>>, TError = ProblemDetails>(
  id: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaterialsId>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiMaterialsIdQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const putApiMaterialsId = (id: string, materialUpdateDto: MaterialUpdateDto, signal?: AbortSignal) => {
  return customInstance<MaterialItem>({
    url: `/api/materials/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: materialUpdateDto,
    signal,
  })
}

export const getPutApiMaterialsIdMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiMaterialsId>>,
    TError,
    { id: string; data: MaterialUpdateDto },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiMaterialsId>>,
  TError,
  { id: string; data: MaterialUpdateDto },
  TContext
> => {
  const mutationKey = ['putApiMaterialsId']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiMaterialsId>>,
    { id: string; data: MaterialUpdateDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return putApiMaterialsId(id, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutApiMaterialsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiMaterialsId>>>
export type PutApiMaterialsIdMutationBody = MaterialUpdateDto
export type PutApiMaterialsIdMutationError = ProblemDetails

export const usePutApiMaterialsId = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiMaterialsId>>,
      TError,
      { id: string; data: MaterialUpdateDto },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiMaterialsId>>,
  TError,
  { id: string; data: MaterialUpdateDto },
  TContext
> => {
  return useMutation(getPutApiMaterialsIdMutationOptions(options), queryClient)
}

export const deleteApiMaterialsId = (id: string, signal?: AbortSignal) => {
  return customInstance<void>({ url: `/api/materials/${id}`, method: 'DELETE', signal })
}

export const getDeleteApiMaterialsIdMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiMaterialsId>>, TError, { id: string }, TContext>
}): UseMutationOptions<Awaited<ReturnType<typeof deleteApiMaterialsId>>, TError, { id: string }, TContext> => {
  const mutationKey = ['deleteApiMaterialsId']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiMaterialsId>>, { id: string }> = (props) => {
    const { id } = props ?? {}

    return deleteApiMaterialsId(id)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteApiMaterialsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiMaterialsId>>>

export type DeleteApiMaterialsIdMutationError = ProblemDetails

export const useDeleteApiMaterialsId = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiMaterialsId>>, TError, { id: string }, TContext>
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteApiMaterialsId>>, TError, { id: string }, TContext> => {
  return useMutation(getDeleteApiMaterialsIdMutationOptions(options), queryClient)
}

export const getApiProducts = (params?: GetApiProductsParams, signal?: AbortSignal) => {
  return customInstance<ProductDto[]>({ url: `/api/products`, method: 'GET', params, signal })
}

export const getGetApiProductsQueryKey = (params?: GetApiProductsParams) => {
  return [`/api/products`, ...(params ? [params] : [])] as const
}

export const getGetApiProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiProducts>>,
  TError = ProblemDetails,
>(
  params?: GetApiProductsParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>> },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetApiProductsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProducts>>> = ({ signal }) =>
    getApiProducts(params, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiProducts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProducts>>>
export type GetApiProductsQueryError = ProblemDetails

export function useGetApiProducts<TData = Awaited<ReturnType<typeof getApiProducts>>, TError = ProblemDetails>(
  params: undefined | GetApiProductsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProducts>>,
          TError,
          Awaited<ReturnType<typeof getApiProducts>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProducts<TData = Awaited<ReturnType<typeof getApiProducts>>, TError = ProblemDetails>(
  params?: GetApiProductsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProducts>>,
          TError,
          Awaited<ReturnType<typeof getApiProducts>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProducts<TData = Awaited<ReturnType<typeof getApiProducts>>, TError = ProblemDetails>(
  params?: GetApiProductsParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiProducts<TData = Awaited<ReturnType<typeof getApiProducts>>, TError = ProblemDetails>(
  params?: GetApiProductsParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiProductsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const postApiProducts = (productPayloadDto: ProductPayloadDto, signal?: AbortSignal) => {
  return customInstance<ProductDto>({
    url: `/api/products`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: productPayloadDto,
    signal,
  })
}

export const getPostApiProductsMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiProducts>>,
    TError,
    { data: ProductPayloadDto },
    TContext
  >
}): UseMutationOptions<Awaited<ReturnType<typeof postApiProducts>>, TError, { data: ProductPayloadDto }, TContext> => {
  const mutationKey = ['postApiProducts']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiProducts>>, { data: ProductPayloadDto }> = (
    props,
  ) => {
    const { data } = props ?? {}

    return postApiProducts(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostApiProductsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiProducts>>>
export type PostApiProductsMutationBody = ProductPayloadDto
export type PostApiProductsMutationError = ProblemDetails

export const usePostApiProducts = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiProducts>>,
      TError,
      { data: ProductPayloadDto },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postApiProducts>>, TError, { data: ProductPayloadDto }, TContext> => {
  return useMutation(getPostApiProductsMutationOptions(options), queryClient)
}

export const getApiProductsAll = (signal?: AbortSignal) => {
  return customInstance<ProductDto[]>({ url: `/api/products/all`, method: 'GET', signal })
}

export const getGetApiProductsAllQueryKey = () => {
  return [`/api/products/all`] as const
}

export const getGetApiProductsAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiProductsAll>>,
  TError = ProblemDetails,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsAll>>, TError, TData>>
}) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetApiProductsAllQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProductsAll>>> = ({ signal }) =>
    getApiProductsAll(signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiProductsAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiProductsAllQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProductsAll>>>
export type GetApiProductsAllQueryError = ProblemDetails

export function useGetApiProductsAll<TData = Awaited<ReturnType<typeof getApiProductsAll>>, TError = ProblemDetails>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsAll>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsAll>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductsAll<TData = Awaited<ReturnType<typeof getApiProductsAll>>, TError = ProblemDetails>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsAll>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsAll>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductsAll<TData = Awaited<ReturnType<typeof getApiProductsAll>>, TError = ProblemDetails>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsAll>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiProductsAll<TData = Awaited<ReturnType<typeof getApiProductsAll>>, TError = ProblemDetails>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsAll>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiProductsAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const getApiProductsSome = (params: GetApiProductsSomeParams, signal?: AbortSignal) => {
  return customInstance<ProductDto[]>({ url: `/api/products/some`, method: 'GET', params, signal })
}

export const getGetApiProductsSomeQueryKey = (params?: GetApiProductsSomeParams) => {
  return [`/api/products/some`, ...(params ? [params] : [])] as const
}

export const getGetApiProductsSomeQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiProductsSome>>,
  TError = ProblemDetails,
>(
  params: GetApiProductsSomeParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsSome>>, TError, TData>> },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetApiProductsSomeQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProductsSome>>> = ({ signal }) =>
    getApiProductsSome(params, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiProductsSome>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiProductsSomeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProductsSome>>>
export type GetApiProductsSomeQueryError = ProblemDetails

export function useGetApiProductsSome<TData = Awaited<ReturnType<typeof getApiProductsSome>>, TError = ProblemDetails>(
  params: GetApiProductsSomeParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsSome>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsSome>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsSome>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductsSome<TData = Awaited<ReturnType<typeof getApiProductsSome>>, TError = ProblemDetails>(
  params: GetApiProductsSomeParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsSome>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsSome>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsSome>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductsSome<TData = Awaited<ReturnType<typeof getApiProductsSome>>, TError = ProblemDetails>(
  params: GetApiProductsSomeParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsSome>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiProductsSome<TData = Awaited<ReturnType<typeof getApiProductsSome>>, TError = ProblemDetails>(
  params: GetApiProductsSomeParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsSome>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiProductsSomeQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const getApiProductsId = (id: string, signal?: AbortSignal) => {
  return customInstance<ProductDto>({ url: `/api/products/${id}`, method: 'GET', signal })
}

export const getGetApiProductsIdQueryKey = (id: string) => {
  return [`/api/products/${id}`] as const
}

export const getGetApiProductsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiProductsId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsId>>, TError, TData>> },
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetApiProductsIdQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProductsId>>> = ({ signal }) =>
    getApiProductsId(id, signal)

  return { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiProductsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiProductsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProductsId>>>
export type GetApiProductsIdQueryError = ProblemDetails

export function useGetApiProductsId<TData = Awaited<ReturnType<typeof getApiProductsId>>, TError = ProblemDetails>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsId>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsId>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductsId<TData = Awaited<ReturnType<typeof getApiProductsId>>, TError = ProblemDetails>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsId>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsId>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsId>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductsId<TData = Awaited<ReturnType<typeof getApiProductsId>>, TError = ProblemDetails>(
  id: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsId>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiProductsId<TData = Awaited<ReturnType<typeof getApiProductsId>>, TError = ProblemDetails>(
  id: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsId>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiProductsIdQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const putApiProductsId = (id: string, productPayloadDto: ProductPayloadDto, signal?: AbortSignal) => {
  return customInstance<ProductDto>({
    url: `/api/products/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: productPayloadDto,
    signal,
  })
}

export const getPutApiProductsIdMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiProductsId>>,
    TError,
    { id: string; data: ProductPayloadDto },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiProductsId>>,
  TError,
  { id: string; data: ProductPayloadDto },
  TContext
> => {
  const mutationKey = ['putApiProductsId']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiProductsId>>,
    { id: string; data: ProductPayloadDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return putApiProductsId(id, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutApiProductsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiProductsId>>>
export type PutApiProductsIdMutationBody = ProductPayloadDto
export type PutApiProductsIdMutationError = ProblemDetails

export const usePutApiProductsId = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiProductsId>>,
      TError,
      { id: string; data: ProductPayloadDto },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiProductsId>>,
  TError,
  { id: string; data: ProductPayloadDto },
  TContext
> => {
  return useMutation(getPutApiProductsIdMutationOptions(options), queryClient)
}

export const deleteApiProductsId = (id: string, signal?: AbortSignal) => {
  return customInstance<void>({ url: `/api/products/${id}`, method: 'DELETE', signal })
}

export const getDeleteApiProductsIdMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiProductsId>>, TError, { id: string }, TContext>
}): UseMutationOptions<Awaited<ReturnType<typeof deleteApiProductsId>>, TError, { id: string }, TContext> => {
  const mutationKey = ['deleteApiProductsId']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiProductsId>>, { id: string }> = (props) => {
    const { id } = props ?? {}

    return deleteApiProductsId(id)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteApiProductsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiProductsId>>>

export type DeleteApiProductsIdMutationError = ProblemDetails

export const useDeleteApiProductsId = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiProductsId>>, TError, { id: string }, TContext>
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteApiProductsId>>, TError, { id: string }, TContext> => {
  return useMutation(getDeleteApiProductsIdMutationOptions(options), queryClient)
}

export const putApiInfoUserId = (id: string, updateInfoUserDto: UpdateInfoUserDto, signal?: AbortSignal) => {
  return customInstance<UpdateInfoUserResponse>({
    url: `/api/info-user/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateInfoUserDto,
    signal,
  })
}

export const getPutApiInfoUserIdMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiInfoUserId>>,
    TError,
    { id: string; data: UpdateInfoUserDto },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiInfoUserId>>,
  TError,
  { id: string; data: UpdateInfoUserDto },
  TContext
> => {
  const mutationKey = ['putApiInfoUserId']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiInfoUserId>>,
    { id: string; data: UpdateInfoUserDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return putApiInfoUserId(id, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutApiInfoUserIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiInfoUserId>>>
export type PutApiInfoUserIdMutationBody = UpdateInfoUserDto
export type PutApiInfoUserIdMutationError = ProblemDetails

export const usePutApiInfoUserId = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiInfoUserId>>,
      TError,
      { id: string; data: UpdateInfoUserDto },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiInfoUserId>>,
  TError,
  { id: string; data: UpdateInfoUserDto },
  TContext
> => {
  return useMutation(getPutApiInfoUserIdMutationOptions(options), queryClient)
}

/**
 * Đăng ký tài khoản dựa vào thông tin gửi lên. Đăng ký thành công thì gửi về một id của người dùng đã đăng ký
 *
 * ### Dữ liệu gửi lên mẫu:
 * ```json
 * {
 *     "firstName": "Nguyễn",
 *     "lastName": "Văn A",
 *     "phone": "0811125678",
 *     "address": "123 Đường Lê Lợi, Quận 1, TP. Hồ Chí Minh",
 *     "role": "User",
 *     "email": "annguynnn111@greeneco.com",
 *     "password": "SecurePassword123jfdlkjkl!"
 * }
 * ```
 */
export const postApiAuthRegister = (registerCommand: RegisterCommand, signal?: AbortSignal) => {
  return customInstance<RegisterResponse>({
    url: `/api/auth/register`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: registerCommand,
    signal,
  })
}

export const getPostApiAuthRegisterMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthRegister>>,
    TError,
    { data: RegisterCommand },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthRegister>>,
  TError,
  { data: RegisterCommand },
  TContext
> => {
  const mutationKey = ['postApiAuthRegister']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRegister>>, { data: RegisterCommand }> = (
    props,
  ) => {
    const { data } = props ?? {}

    return postApiAuthRegister(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostApiAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRegister>>>
export type PostApiAuthRegisterMutationBody = RegisterCommand
export type PostApiAuthRegisterMutationError = ProblemDetails

export const usePostApiAuthRegister = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthRegister>>,
      TError,
      { data: RegisterCommand },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postApiAuthRegister>>, TError, { data: RegisterCommand }, TContext> => {
  return useMutation(getPostApiAuthRegisterMutationOptions(options), queryClient)
}

export const postApiAuthLogin = (loginCommand: LoginCommand, signal?: AbortSignal) => {
  return customInstance<UserInfoResponse>({
    url: `/api/auth/login`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: loginCommand,
    signal,
  })
}

export const getPostApiAuthLoginMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError, { data: LoginCommand }, TContext>
}): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError, { data: LoginCommand }, TContext> => {
  const mutationKey = ['postApiAuthLogin']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthLogin>>, { data: LoginCommand }> = (
    props,
  ) => {
    const { data } = props ?? {}

    return postApiAuthLogin(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostApiAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthLogin>>>
export type PostApiAuthLoginMutationBody = LoginCommand
export type PostApiAuthLoginMutationError = ProblemDetails

export const usePostApiAuthLogin = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthLogin>>,
      TError,
      { data: LoginCommand },
      TContext
    >
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postApiAuthLogin>>, TError, { data: LoginCommand }, TContext> => {
  return useMutation(getPostApiAuthLoginMutationOptions(options), queryClient)
}

export const postApiAuthLogout = (signal?: AbortSignal) => {
  return customInstance<unknown | void>({ url: `/api/auth/logout`, method: 'POST', signal })
}

export const getPostApiAuthLogoutMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogout>>, TError, void, TContext>
}): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogout>>, TError, void, TContext> => {
  const mutationKey = ['postApiAuthLogout']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthLogout>>, void> = () => {
    return postApiAuthLogout()
  }

  return { mutationFn, ...mutationOptions }
}

export type PostApiAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthLogout>>>

export type PostApiAuthLogoutMutationError = ProblemDetails

export const usePostApiAuthLogout = <TError = ProblemDetails, TContext = unknown>(
  options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogout>>, TError, void, TContext> },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postApiAuthLogout>>, TError, void, TContext> => {
  return useMutation(getPostApiAuthLogoutMutationOptions(options), queryClient)
}

export const getApiAuthMe = (signal?: AbortSignal) => {
  return customInstance<UserProfileResponse>({ url: `/api/auth/me`, method: 'GET', signal })
}

export const getGetApiAuthMeQueryKey = () => {
  return [`/api/auth/me`] as const
}

export const getGetApiAuthMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAuthMe>>,
  TError = ProblemDetails,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>>
}) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetApiAuthMeQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthMe>>> = ({ signal }) => getApiAuthMe(signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAuthMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthMe>>>
export type GetApiAuthMeQueryError = ProblemDetails

export function useGetApiAuthMe<TData = Awaited<ReturnType<typeof getApiAuthMe>>, TError = ProblemDetails>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthMe>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthMe<TData = Awaited<ReturnType<typeof getApiAuthMe>>, TError = ProblemDetails>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthMe>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthMe<TData = Awaited<ReturnType<typeof getApiAuthMe>>, TError = ProblemDetails>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAuthMe<TData = Awaited<ReturnType<typeof getApiAuthMe>>, TError = ProblemDetails>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiAuthMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const postApiAuthRefreshToken = (signal?: AbortSignal) => {
  return customInstance<void>({ url: `/api/auth/refresh-token`, method: 'POST', signal })
}

export const getPostApiAuthRefreshTokenMutationOptions = <TError = ProblemDetails, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefreshToken>>, TError, void, TContext>
}): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefreshToken>>, TError, void, TContext> => {
  const mutationKey = ['postApiAuthRefreshToken']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRefreshToken>>, void> = () => {
    return postApiAuthRefreshToken()
  }

  return { mutationFn, ...mutationOptions }
}

export type PostApiAuthRefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRefreshToken>>>

export type PostApiAuthRefreshTokenMutationError = ProblemDetails

export const usePostApiAuthRefreshToken = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefreshToken>>, TError, void, TContext>
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postApiAuthRefreshToken>>, TError, void, TContext> => {
  return useMutation(getPostApiAuthRefreshTokenMutationOptions(options), queryClient)
}

export const getApiTest = (signal?: AbortSignal) => {
  return customInstance<void>({ url: `/api/test`, method: 'GET', signal })
}

export const getGetApiTestQueryKey = () => {
  return [`/api/test`] as const
}

export const getGetApiTestQueryOptions = <TData = Awaited<ReturnType<typeof getApiTest>>, TError = unknown>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTest>>, TError, TData>>
}) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetApiTestQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTest>>> = ({ signal }) => getApiTest(signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiTest>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTestQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTest>>>
export type GetApiTestQueryError = unknown

export function useGetApiTest<TData = Awaited<ReturnType<typeof getApiTest>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTest>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTest>>,
          TError,
          Awaited<ReturnType<typeof getApiTest>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTest<TData = Awaited<ReturnType<typeof getApiTest>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTest>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTest>>,
          TError,
          Awaited<ReturnType<typeof getApiTest>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTest<TData = Awaited<ReturnType<typeof getApiTest>>, TError = unknown>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTest>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiTest<TData = Awaited<ReturnType<typeof getApiTest>>, TError = unknown>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTest>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiTestQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const deleteApiTestId = (id: string, signal?: AbortSignal) => {
  return customInstance<void>({ url: `/api/test/${id}`, method: 'DELETE', signal })
}

export const getDeleteApiTestIdMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiTestId>>, TError, { id: string }, TContext>
}): UseMutationOptions<Awaited<ReturnType<typeof deleteApiTestId>>, TError, { id: string }, TContext> => {
  const mutationKey = ['deleteApiTestId']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiTestId>>, { id: string }> = (props) => {
    const { id } = props ?? {}

    return deleteApiTestId(id)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteApiTestIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiTestId>>>

export type DeleteApiTestIdMutationError = unknown

export const useDeleteApiTestId = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiTestId>>, TError, { id: string }, TContext>
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteApiTestId>>, TError, { id: string }, TContext> => {
  return useMutation(getDeleteApiTestIdMutationOptions(options), queryClient)
}
