/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * GreenEcoCommerce.WebAPI | v1
 * OpenAPI spec version: 1.0.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { useMutation, useQuery } from '@tanstack/react-query'
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios'
import * as axios from 'axios'

import type { LoginCommand, ProblemDetails, RegisterCommand } from './schemas'

/**
 * Đăng ký tài khoản dựa vào thông tin gửi lên. Đăng ký thành công thì gửi về một id của người dùng đã đăng ký
 *
 * ### Dữ liệu gửi lên mẫu:
 * ```json
 * {
 *     "firstName": "Nguyễn",
 *     "lastName": "Văn A",
 *     "phone": "0811125678",
 *     "address": "123 Đường Lê Lợi, Quận 1, TP. Hồ Chí Minh",
 *     "role": "User",
 *     "email": "annguynnn111@greeneco.com",
 *     "password": "SecurePassword123jfdlkjkl!"
 * }
 * ```
 */
export const postApiAuthRegister = (
  registerCommand: RegisterCommand,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.default.post(`/api/Auth/register`, registerCommand, options)
}

export const getPostApiAuthRegisterMutationOptions = <
  TError = AxiosError<ProblemDetails>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthRegister>>,
    TError,
    { data: RegisterCommand },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthRegister>>,
  TError,
  { data: RegisterCommand },
  TContext
> => {
  const mutationKey = ['postApiAuthRegister']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRegister>>, { data: RegisterCommand }> = (
    props,
  ) => {
    const { data } = props ?? {}

    return postApiAuthRegister(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostApiAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRegister>>>
export type PostApiAuthRegisterMutationBody = RegisterCommand
export type PostApiAuthRegisterMutationError = AxiosError<ProblemDetails>

export const usePostApiAuthRegister = <TError = AxiosError<ProblemDetails>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthRegister>>,
      TError,
      { data: RegisterCommand },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postApiAuthRegister>>, TError, { data: RegisterCommand }, TContext> => {
  return useMutation(getPostApiAuthRegisterMutationOptions(options), queryClient)
}

export const postApiAuthLogin = (
  loginCommand: LoginCommand,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.default.post(`/api/Auth/login`, loginCommand, options)
}

export const getPostApiAuthLoginMutationOptions = <TError = AxiosError<ProblemDetails>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError, { data: LoginCommand }, TContext>
  axios?: AxiosRequestConfig
}): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError, { data: LoginCommand }, TContext> => {
  const mutationKey = ['postApiAuthLogin']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthLogin>>, { data: LoginCommand }> = (
    props,
  ) => {
    const { data } = props ?? {}

    return postApiAuthLogin(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostApiAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthLogin>>>
export type PostApiAuthLoginMutationBody = LoginCommand
export type PostApiAuthLoginMutationError = AxiosError<ProblemDetails>

export const usePostApiAuthLogin = <TError = AxiosError<ProblemDetails>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthLogin>>,
      TError,
      { data: LoginCommand },
      TContext
    >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postApiAuthLogin>>, TError, { data: LoginCommand }, TContext> => {
  return useMutation(getPostApiAuthLoginMutationOptions(options), queryClient)
}

export const getApiTest = (options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.default.get(`/api/Test`, options)
}

export const getGetApiTestQueryKey = () => {
  return [`/api/Test`] as const
}

export const getGetApiTestQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiTest>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTest>>, TError, TData>>
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetApiTestQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTest>>> = ({ signal }) =>
    getApiTest({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiTest>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTestQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTest>>>
export type GetApiTestQueryError = AxiosError<unknown>

export function useGetApiTest<TData = Awaited<ReturnType<typeof getApiTest>>, TError = AxiosError<unknown>>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTest>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTest>>,
          TError,
          Awaited<ReturnType<typeof getApiTest>>
        >,
        'initialData'
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTest<TData = Awaited<ReturnType<typeof getApiTest>>, TError = AxiosError<unknown>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTest>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTest>>,
          TError,
          Awaited<ReturnType<typeof getApiTest>>
        >,
        'initialData'
      >
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTest<TData = Awaited<ReturnType<typeof getApiTest>>, TError = AxiosError<unknown>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTest>>, TError, TData>>
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiTest<TData = Awaited<ReturnType<typeof getApiTest>>, TError = AxiosError<unknown>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTest>>, TError, TData>>
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiTestQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const deleteApiTestId = (id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.default.delete(`/api/Test/${id}`, options)
}

export const getDeleteApiTestIdMutationOptions = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiTestId>>, TError, { id: string }, TContext>
  axios?: AxiosRequestConfig
}): UseMutationOptions<Awaited<ReturnType<typeof deleteApiTestId>>, TError, { id: string }, TContext> => {
  const mutationKey = ['deleteApiTestId']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiTestId>>, { id: string }> = (props) => {
    const { id } = props ?? {}

    return deleteApiTestId(id, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteApiTestIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiTestId>>>

export type DeleteApiTestIdMutationError = AxiosError<unknown>

export const useDeleteApiTestId = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiTestId>>, TError, { id: string }, TContext>
    axios?: AxiosRequestConfig
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteApiTestId>>, TError, { id: string }, TContext> => {
  return useMutation(getDeleteApiTestIdMutationOptions(options), queryClient)
}
